export type RecommendationType = 'recommendation' | 'endorsement'
export type RecommendationLanguage = 'en' | 'fr' | 'pt' | 'ar'

export const recommendationTranslations = {
  en: {
    recommendationTitle: 'Letter of Recommendation',
    endorsementTitle: 'Professional Endorsement',
    toWhomItMayConcern: 'To Whom It May Concern,',
    recommendationBody: (studentName: string, programTitle: string) =>
      `I am pleased to provide this letter of recommendation for ${studentName}, who has successfully completed the professional certification in ${programTitle} at IICAR Professional School. Throughout the program, ${studentName} demonstrated exceptional commitment to learning, outstanding technical proficiency, and a comprehensive grasp of the course material.\n\n${studentName} consistently displayed a strong work ethic, excellent problem-solving abilities, and the capacity to apply theoretical knowledge to practical situations. Their engagement with peers and instructors was professional and collaborative, contributing positively to the learning environment.\n\nThe competencies acquired during this certification program have prepared ${studentName} to excel in professional roles requiring specialized expertise and leadership qualities. Based on the demonstrated performance and achievements throughout the program, I am confident that ${studentName} possesses the knowledge, skills, and character to succeed in advancing their professional career.`,
    endorsementBody: (studentName: string, programTitle: string) =>
      `This is to certify that ${studentName} has successfully completed and demonstrated professional competency and mastery in the ${programTitle} certification program offered by IICAR Professional School. Throughout the intensive training and assessment process, ${studentName} exhibited exceptional technical proficiency and a thorough understanding of industry-relevant practices.\n\nThe skills and knowledge acquired include advanced technical competencies, professional methodologies, and best practices in the field. ${studentName} has proven the ability to apply these competencies effectively in professional contexts and to continue developing expertise independently.\n\nWe hereby endorse ${studentName}'s professional qualifications and competency in ${programTitle}. This certification represents a verified achievement of professional standards and readiness for advancement in the field.`,
    conclusion: 'I am confident that this individual will make a valuable contribution to any organization and am available to discuss their qualifications in further detail upon request.',
    sincerely: 'Sincerely,',
    registrar: 'Office of the Registrar',
    directorPrograms: 'Director, Professional Programs',
    icarAcademy: 'IICAR Professional School',
    generatedDate: 'Generated Date:',
    multipleRecommendationIntro: (studentName: string) =>
      `This letter of recommendation is provided for ${studentName}, who has successfully completed the following professional certification program(s) at IICAR Global College:`,
    multipleEndorsementIntro: (studentName: string) =>
      `This professional endorsement is provided for ${studentName}, who has successfully completed and demonstrated competency in the following professional certification program(s) at IICAR Global College:`,
    multipleRecommendationBody: (studentName: string) =>
      `Throughout these professional development programs, ${studentName} demonstrated exceptional commitment to learning, outstanding technical proficiency, and comprehensive understanding of the subject matter. ${studentName} consistently displayed strong work ethic, excellent problem-solving abilities, and the capacity to apply theoretical knowledge to practical situations.\n\nThe completion of these multiple certifications demonstrates ${studentName}'s dedication to professional development and mastery of diverse professional competencies. This individual is well-prepared to apply these skills in professional roles requiring specialized expertise and leadership qualities.`,
    multipleEndorsementBody: (studentName: string) =>
      `Through the completion of these professional certification programs, ${studentName} has demonstrated exceptional technical proficiency and mastery of industry-relevant practices across multiple specialized domains. The skills and knowledge acquired through these comprehensive programs include advanced technical competencies, professional methodologies, and best practices in multiple fields.\n\n${studentName} has proven the ability to apply these competencies effectively in professional contexts and to continue developing expertise independently. These multiple certifications represent verified achievement of professional standards and readiness for advancement in multiple professional domains.`,
  },
  fr: {
    recommendationTitle: 'Lettre de Recommandation',
    endorsementTitle: 'Approbation Professionnelle',
    toWhomItMayConcern: 'À qui de droit,',
    recommendationBody: (studentName: string, programTitle: string) =>
      `Je suis heureux de fournir cette lettre de recommandation pour ${studentName}, qui a complété avec succès la certification professionnelle en ${programTitle} à l'École Professionnelle IICAR. Tout au long du programme, ${studentName} a démontré un engagement exceptionnel envers l'apprentissage, une maîtrise technique exceptionnelle et une compréhension approfondie de la matière du cours.\n\n${studentName} a constamment affiché une forte éthique de travail, d'excellentes capacités de résolution de problèmes et la capacité à appliquer les connaissances théoriques à des situations pratiques. Son engagement auprès des pairs et des instructeurs a été professionnel et collaboratif, contribuant positivement à l'environnement d'apprentissage.\n\nLes compétences acquises au cours de ce programme de certification ont préparé ${studentName} à exceller dans les rôles professionnels exigeant une expertise spécialisée et des qualités de leadership. Sur la base de la performance et des réalisations démontrées tout au long du programme, je suis confiant que ${studentName} possède les connaissances, les compétences et le caractère pour réussir à faire progresser sa carrière professionnelle.`,
    endorsementBody: (studentName: string, programTitle: string) =>
      `Ceci certifie que ${studentName} a complété avec succès et démontré une compétence professionnelle et une maîtrise du programme de certification ${programTitle} offert par l'École Professionnelle IICAR. Tout au long du processus de formation et d'évaluation intensif, ${studentName} a affiché une compétence technique exceptionnelle et une compréhension approfondie des pratiques pertinentes à l'industrie.\n\nLes compétences et connaissances acquises incluent des compétences techniques avancées, des méthodologies professionnelles et les meilleures pratiques du domaine. ${studentName} a prouvé la capacité à appliquer ces compétences efficacement dans des contextes professionnels et à continuer à développer son expertise de manière indépendante.\n\nNous approuvons par la présente les qualifications professionnelles et la compétence de ${studentName} en ${programTitle}. Cette certification représente une réalisation vérifiée des normes professionnelles et l'état de préparation pour l'avancement dans le domaine.`,
    conclusion: 'Je suis confiant que cette personne apportera une contribution précieuse à toute organisation et je suis disponible pour discuter de ses qualifications de manière plus détaillée si demandé.',
    sincerely: 'Sincèrement,',
    registrar: 'Bureau du Registraire',
    directorPrograms: 'Directeur, Programmes Professionnels',
    icarAcademy: 'École Professionnelle IICAR',
    generatedDate: 'Date de génération :',
    multipleRecommendationIntro: (studentName: string) =>
      `Cette lettre de recommandation est fournie pour ${studentName}, qui a complété avec succès le(s) programme(s) de certification professionnelle suivant(s) au Collège Mondial IICAR :`,
    multipleEndorsementIntro: (studentName: string) =>
      `Cette approbation professionnelle est fournie pour ${studentName}, qui a complété avec succès et démontré sa compétence dans le(s) programme(s) de certification professionnelle suivant(s) au Collège Mondial IICAR :`,
    multipleRecommendationBody: (studentName: string) =>
      `Tout au long de ces programmes de développement professionnel, ${studentName} a démontré un engagement exceptionnel envers l'apprentissage, une maîtrise technique exceptionnelle et une compréhension complète de la matière. ${studentName} a constamment affiché une forte éthique de travail, d'excellentes capacités de résolution de problèmes et la capacité à appliquer les connaissances théoriques à des situations pratiques.\n\nL'achèvement de ces certifications multiples démontre le dévouement de ${studentName} envers le développement professionnel et la maîtrise de compétences professionnelles diverses. Cette personne est bien préparée pour appliquer ces compétences dans des rôles professionnels exigeant une expertise spécialisée et des qualités de leadership.`,
    multipleEndorsementBody: (studentName: string) =>
      `Grâce à l'achèvement de ces programmes de certification professionnelle, ${studentName} a démontré une proficiency technique exceptionnelle et une maîtrise des pratiques pertinentes à l'industrie dans plusieurs domaines spécialisés. Les compétences et connaissances acquises grâce à ces programmes complets incluent des compétences techniques avancées, des méthodologies professionnelles et les meilleures pratiques dans plusieurs domaines.\n\n${studentName} a prouvé la capacité à appliquer ces compétences efficacement dans des contextes professionnels et à continuer à développer son expertise de manière indépendante. Ces certifications multiples représentent une réalisation vérifiée des normes professionnelles et l'état de préparation pour l'avancement dans plusieurs domaines professionnels.`,
  },
  pt: {
    recommendationTitle: 'Carta de Recomendação',
    endorsementTitle: 'Aprovação Profissional',
    toWhomItMayConcern: 'A quem interessar possa,',
    recommendationBody: (studentName: string, programTitle: string) =>
      `Tenho o prazer de fornecer esta carta de recomendação para ${studentName}, que completou com sucesso a certificação profissional em ${programTitle} na Escola Profissional IICAR. Durante o programa, ${studentName} demonstrou comprometimento excepcional com a aprendizagem, proficiência técnica notável e compreensão sólida do material do curso.\n\n${studentName} demonstrou consistentemente uma forte ética de trabalho, excelentes capacidades de resolução de problemas e a capacidade de aplicar conhecimento teórico a situações práticas. Seu envolvimento com colegas e instrutores foi profissional e colaborativo, contribuindo positivamente para o ambiente de aprendizagem.\n\nAs competências adquiridas durante este programa de certificação prepararam ${studentName} para se destacar em funções profissionais que exigem experiência especializada e qualidades de liderança. Com base no desempenho demonstrado e realizações ao longo do programa, tenho confiança de que ${studentName} possui o conhecimento, habilidades e caráter para ter sucesso no avanço de sua carreira profissional.`,
    endorsementBody: (studentName: string, programTitle: string) =>
      `Isto certifica que ${studentName} completou com sucesso e demonstrou competência profissional e domínio do programa de certificação ${programTitle} oferecido pela Escola Profissional IICAR. Ao longo do processo intensivo de treinamento e avaliação, ${studentName} exibiu proficiência técnica excepcional e compreensão profunda das práticas relevantes da indústria.\n\nAs habilidades e conhecimentos adquiridos incluem competências técnicas avançadas, metodologias profissionais e melhores práticas do campo. ${studentName} provou a capacidade de aplicar essas competências efetivamente em contextos profissionais e de continuar desenvolvendo expertise de forma independente.\n\nPor este meio endossamos as qualificações profissionais e a competência de ${studentName} em ${programTitle}. Esta certificação representa uma realização verificada dos padrões profissionais e prontidão para avanço no campo.`,
    conclusion: 'Tenho confiança de que este indivíduo fará uma contribuição valiosa para qualquer organização e fico feliz em discutir suas qualificações em maior detalhe se solicitado.',
    sincerely: 'Atenciosamente,',
    registrar: 'Gabinete do Registrador',
    directorPrograms: 'Diretor, Programas Profissionais',
    icarAcademy: 'Escola Profissional IICAR',
    generatedDate: 'Data de Geração:',
    multipleRecommendationIntro: (studentName: string) =>
      `Esta carta de recomendação é fornecida para ${studentName}, que completou com sucesso o(s) seguinte(s) programa(s) de certificação profissional no Faculdade Global IICAR:`,
    multipleEndorsementIntro: (studentName: string) =>
      `Esta aprovação profissional é fornecida para ${studentName}, que completou com sucesso e demonstrou competência no(s) seguinte(s) programa(s) de certificação profissional no Faculdade Global IICAR:`,
    multipleRecommendationBody: (studentName: string) =>
      `Ao longo desses programas de desenvolvimento profissional, ${studentName} demonstrou comprometimento excepcional com a aprendizagem, proficiência técnica notável e compreensão completa do assunto. ${studentName} demonstrou consistentemente uma forte ética de trabalho, excelentes capacidades de resolução de problemas e a capacidade de aplicar conhecimento teórico a situações práticas.\n\nA conclusão de múltiplas certificações demonstra o compromisso de ${studentName} com o desenvolvimento profissional e o domínio de competências profissionais diversas. Este indivíduo está bem preparado para aplicar essas habilidades em funções profissionais que exigem experiência especializada e qualidades de liderança.`,
    multipleEndorsementBody: (studentName: string) =>
      `Através da conclusão desses programas de certificação profissional, ${studentName} demonstrou proficiência técnica excepcional e domínio das práticas relevantes da indústria em múltiplos domínios especializados. As habilidades e conhecimentos adquiridos através desses programas abrangentes incluem competências técnicas avançadas, metodologias profissionais e melhores práticas em múltiplos campos.\n\n${studentName} provou a capacidade de aplicar essas competências efetivamente em contextos profissionais e de continuar desenvolvendo expertise de forma independente. Essas múltiplas certificações representam uma realização verificada dos padrões profissionais e prontidão para avanço em múltiplos domínios profissionais.`,
  },
  ar: {
    recommendationTitle: 'خطاب توصية',
    endorsementTitle: 'شهادة تصديق مهنية',
    toWhomItMayConcern: 'إلى من يهمه الأمر،',
    recommendationBody: (studentName: string, programTitle: string) =>
      `يسعدني تقديم خطاب التوصية هذا لـ ${studentName}، الذي أكمل بنجاح برنامج الشهادة المهنية في مجال ${programTitle} بمدرسة IICAR المهنية. وطوال فترة الدراسة، أظهر ${studentName} التزاماً استثنائياً بالتعلم والتطور المهني، وإتقاناً تقنياً ملحوظاً، وفهماً شاملاً وعميقاً لمحتوى المقرر الدراسي.\n\nأظهر ${studentName} باستمرار أخلاقيات عمل قوية جداً وقدرات ممتازة في حل المشاكل المعقدة، والقدرة على تطبيق المعرفة النظرية على الحالات والمواقف العملية الحقيقية. كان تعاونه مع زملائه والمدربين احترافياً وفعّالاً، مما أسهم بشكل إيجابي ملحوظ في بيئة التعلم والدراسة.\n\nلقد أعد هذا البرنامج ${studentName} للتفوق والنجاح في الأدوار الوظيفية والمهنية التي تتطلب خبرة متخصصة وقدرات قيادية قوية. وبناءً على الأداء المميز والإنجازات التي حققها طوال فترة البرنامج، أنا واثق تماماً من أن ${studentName} يمتلك المعرفة والمهارات والنزاهة اللازمة للنجاح والتقدم بنجاح في مساره الوظيفي والمهني.`,
    endorsementBody: (studentName: string, programTitle: string) =>
      `تشهد هذه الوثيقة الرسمية بأن ${studentName} قد أكمل بنجاح برنامج الشهادة المهنية في مجال ${programTitle} المقدم من قبل مدرسة IICAR المهنية، وأثبت الكفاءة المهنية العالية والإتقان التام للمهارات المطلوبة والمتوقعة. وطوال عملية التدريب والتقييم الشاملة والمكثفة والصارمة، أظهر ${studentName} مستويات عالية جداً من الكفاءة التقنية والمهارة وفهماً عميقاً وشاملاً للممارسات الصناعية الحديثة والمتقدمة.\n\nتشمل المهارات والمعارف المكتسبة والمتحصل عليها الكفاءات التقنية المتقدمة والمتطورة والمنهجيات المهنية الحديثة وأفضل الممارسات المعترف بها والمشهورة في المجال والقطاع. وقد أثبت ${studentName} القدرة الفعّالة والقوية على تطبيق هذه الكفاءات بكفاءة عالية في السياقات والبيئات المهنية الحقيقية والعملية والاستمرار في تطوير الخبرة والمهارات بشكل مستقل ومثابر.\n\nنصادق بموجب هذه الوثيقة الرسمية على المؤهلات المهنية والكفاءة العملية العالية لـ ${studentName} في مجال ${programTitle}. وتمثل هذه الشهادة اعترافاً رسمياً ومعتمداً بإنجاز معايير مهنية عالية جداً والاستعداد الكامل والشامل للتقدم والتطور والتقدم الوظيفي في المجال والقطاع.`,
    conclusion: 'أنا واثق تماماً من أن هذا الشخص سيقدم مساهمات قيمة وفعّالة وملموسة لأي منظمة أو مؤسسة، وأنا متاح ومستعد لمناقشة مؤهلاته وكفاءاته بمزيد من التفاصيل والتوضيح عند الحاجة والطلب.',
    sincerely: 'مع أطيب التحيات وأفضل الأمنيات،',
    registrar: 'مكتب المسجل',
    directorPrograms: 'مدير البرامج والشهادات المهنية',
    icarAcademy: 'مدرسة IICAR المهنية',
    generatedDate: 'تاريخ الإنشاء والإصدار:',
    multipleRecommendationIntro: (studentName: string) =>
      `يتم تقديم خطاب التوصية هذا لـ ${studentName}، الذي أكمل بنجاح برامج الشهادات المهنية التالية بكلية IICAR العالمية:`,
    multipleEndorsementIntro: (studentName: string) =>
      `يتم تقديم شهادة التصديق المهنية هذه لـ ${studentName}، الذي أكمل بنجاح برامج الشهادات المهنية التالية وأثبت الكفاءة العالية فيها جميعاً بكلية IICAR العالمية:`,
    multipleRecommendationBody: (studentName: string) =>
      `طوال هذه البرامج المتعددة للتطوير والتدريب المهني، أظهر ${studentName} التزاماً استثنائياً بالتعلم والتطور المستمر، وإتقاناً تقنياً ملحوظاً جداً، وفهماً شاملاً وعميقاً للمواضيع والموضوعات المختلفة والمتنوعة. وأظهر ${studentName} باستمرار أخلاقيات عمل قوية جداً وقدرات متميزة وممتازة في حل المشاكل المعقدة والصعبة والقدرة الفعّالة على تطبيق المعرفة النظرية على الحالات والمواقف العملية الواقعية والحقيقية.\n\nيوضح إكمال هذه الشهادات المتعددة والمتنوعة التزام ${studentName} القوي الراسخ بالتطوير المهني المستمر والمتواصل وإتقانه لمجموعة واسعة ومتنوعة من الكفاءات المهنية والمهارات المختلفة. وهذا الشخص مستعد جيداً جداً وقادر على تطبيق هذه المهارات والمعارف الكثيرة في الأدوار الوظيفية المتقدمة والعليا التي تتطلب خبرة متخصصة وقدرات قيادية قوية جداً.`,
    multipleEndorsementBody: (studentName: string) =>
      `من خلال إكمال هذه البرامج المتعددة والمختلفة للشهادات المهنية، أظهر ${studentName} مستويات عالية جداً من الكفاءة التقنية والمهارة والإتقان الكامل للممارسات الصناعية الحديثة والمتقدمة والمتطورة عبر مجالات متخصصة ومتعددة ومختلفة. وتشمل المهارات والمعارف المكتسبة والمتحصل عليها من خلال هذه البرامج الشاملة والمتطورة والمتقدمة الكفاءات التقنية المتقدمة والمتطورة والمنهجيات المهنية الحديثة وأفضل الممارسات المعترف بها والمشهورة في حقول ومجالات عديدة ومختلفة.\n\nأثبت ${studentName} القدرة القوية والفعّالة على تطبيق هذه الكفاءات بكفاءة عالية جداً في السياقات والبيئات المهنية الحقيقية والعملية والاستمرار في تطوير الخبرة والمهارات والمعارف بشكل مستقل ومثابر ومتواصل. وتمثل هذه الشهادات المتعددة والمختلفة اعترافاً رسمياً ومعتمداً بإنجاز معايير مهنية عالية جداً والاستعداد الكامل والشامل للتقدم والتطور الوظيفي والمهني في مجالات مهنية متعددة ومختلفة.`,
  },
}
